name: Docker

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker build . --tag ghcr.io/${{ github.repository }}:$GITHUB_SHA --cache-from ghcr.io/${{ github.repository }}:latest
          docker tag ghcr.io/${{ github.repository }}:$GITHUB_SHA ghcr.io/${{ github.repository }}:latest

      - name: Log into registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Push image
        run: |
          docker push --all-tags ghcr.io/${{ github.repository }}
